### ISSUE TITLE
Roadmap 2014-2015

### ISSUE THREAD

**Issue by MrSaints** [MrSaints/Morphist#1]
If you need assistance with the plugin but you do not have a Github or a Twitter account, you can drop a question at my [Ask.fm](http://ask.fm/worldwidewhatever).

_I'll be using this as a personal issue, feature and idea dump._
# TODO

The list of items below are ALL under consideration. They may or may not be added / completed.
## Enhancements
- [x] Demo page: syntax highlighting, hide X scroll (3289f60b2d117378afdbd6deaa0fbdedd5582013)
- [ ] Add information on how to stop and restart the animation cycle (aka, how to use `complete`)
- [ ] New landing page (???)
- [ ] IRC information for alternative mode of contact
- [ ] WordPress plugin (???)
## New features
- [x] Enable / disable auto cycling method (142ae594d472e4acce3f404dbbc7df86ad0f833f)
- [ ] Jump to X / Y method (it can _already be done_ by changing the `index` value)
- [ ] Next / previous method (it can _already be done_ by stopping the cycle and calling the `loop` manually)
- [ ] Randomise (being worked on in [feature-randomization](https://github.com/MrSaints/Morphist/tree/feature-randomization))
- [ ] Shuffle
- [ ] Plugin: typewriter effect (???)
## Bugs
- [x] Potential conflict in class resulting in no transition (f3f31059816dc420da5a0377d2346f8cfd836f98)
